"""
Report Generation Utility - Export analysis results as downloadable HTML reports.
"""

import streamlit as st
import pandas as pd
import numpy as np
import io
from datetime import datetime


def generate_report_html(title: str, sections: list) -> str:
    """Generate an HTML report from sections.

    Each section is a dict with:
        - 'title': str
        - 'content': str (HTML) or pd.DataFrame or plotly Figure
    """
    css = """
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px;
               color: #1e293b; background: #f8fafc; }
        h1 { color: #6366f1; border-bottom: 3px solid #6366f1; padding-bottom: 10px; }
        h2 { color: #334155; margin-top: 30px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
        table { border-collapse: collapse; width: 100%; margin: 16px 0; }
        th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
        th { background: #f1f5f9; font-weight: 600; }
        tr:nth-child(even) { background: #f8fafc; }
        .metric { display: inline-block; background: #fff; border: 1px solid #e2e8f0;
                   border-radius: 8px; padding: 12px 20px; margin: 6px; text-align: center; }
        .metric-value { font-size: 1.4em; font-weight: 700; color: #6366f1; }
        .metric-label { font-size: 0.85em; color: #64748b; }
        .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0;
                   color: #94a3b8; font-size: 0.85em; }
        .chart-container { margin: 16px 0; }
    </style>
    """

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    html_parts = [
        "<!DOCTYPE html><html><head><meta charset='utf-8'>",
        f"<title>{title}</title>",
        css,
        "<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>",
        "</head><body>",
        f"<h1>{title}</h1>",
        f"<p style='color: #64748b;'>Generated: {now}</p>",
    ]

    for section in sections:
        html_parts.append(f"<h2>{section['title']}</h2>")
        content = section["content"]

        if isinstance(content, pd.DataFrame):
            html_parts.append(content.to_html(index=False, classes="report-table"))
        elif hasattr(content, "to_html"):
            # Plotly figure
            html_parts.append('<div class="chart-container">')
            html_parts.append(content.to_html(full_html=False, include_plotlyjs=False))
            html_parts.append("</div>")
        else:
            html_parts.append(str(content))

    html_parts.append(
        '<div class="footer">Generated by Ryan\'s Data Lab</div>'
    )
    html_parts.append("</body></html>")
    return "\n".join(html_parts)


def render_download_report_button(title: str, sections: list, key: str = "dl_report"):
    """Render a download button for an HTML report."""
    html = generate_report_html(title, sections)
    st.download_button(
        label="Download Report (HTML)",
        data=html,
        file_name=f"{title.lower().replace(' ', '_')}_report.html",
        mime="text/html",
        key=key,
    )
