"""
Report Builder - Full report assembly, section management, and multi-format export
(HTML, PDF via fpdf2, PowerPoint via python-pptx).
"""

import io
from datetime import datetime

import pandas as pd
import numpy as np
import streamlit as st

from modules.ui_helpers import section_header, empty_state, help_tip, rdl_plotly_chart

# ─── Optional dependency imports ─────────────────────────────────────────────

_HAS_FPDF = True
try:
    from fpdf import FPDF
except ImportError:
    _HAS_FPDF = False

_HAS_PPTX = True
try:
    from pptx import Presentation
    from pptx.util import Inches, Pt, Emu
    from pptx.enum.text import PP_ALIGN
except ImportError:
    _HAS_PPTX = False


# ─── Existing HTML export helpers (unchanged) ───────────────────────────────

def generate_report_html(title: str, sections: list) -> str:
    """Generate an HTML report from sections.

    Each section is a dict with:
        - 'title': str
        - 'content': str (HTML) or pd.DataFrame or plotly Figure
    """
    css = """
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px;
               color: #1e293b; background: #f8fafc; }
        h1 { color: #6366f1; border-bottom: 3px solid #6366f1; padding-bottom: 10px; }
        h2 { color: #334155; margin-top: 30px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
        table { border-collapse: collapse; width: 100%; margin: 16px 0; }
        th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
        th { background: #f1f5f9; font-weight: 600; }
        tr:nth-child(even) { background: #f8fafc; }
        .metric { display: inline-block; background: #fff; border: 1px solid #e2e8f0;
                   border-radius: 8px; padding: 12px 20px; margin: 6px; text-align: center; }
        .metric-value { font-size: 1.4em; font-weight: 700; color: #6366f1; }
        .metric-label { font-size: 0.85em; color: #64748b; }
        .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0;
                   color: #94a3b8; font-size: 0.85em; }
        .chart-container { margin: 16px 0; }
    </style>
    """

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    html_parts = [
        "<!DOCTYPE html><html><head><meta charset='utf-8'>",
        f"<title>{title}</title>",
        css,
        "<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>",
        "</head><body>",
        f"<h1>{title}</h1>",
        f"<p style='color: #64748b;'>Generated: {now}</p>",
    ]

    for section in sections:
        html_parts.append(f"<h2>{section['title']}</h2>")
        content = section["content"]

        if isinstance(content, pd.DataFrame):
            html_parts.append(content.to_html(index=False, classes="report-table"))
        elif hasattr(content, "to_html"):
            # Plotly figure
            html_parts.append('<div class="chart-container">')
            html_parts.append(content.to_html(full_html=False, include_plotlyjs=False))
            html_parts.append("</div>")
        else:
            html_parts.append(str(content))

        # Append commentary if present
        commentary = section.get("commentary", "")
        if commentary:
            html_parts.append(f"<p><em>{commentary}</em></p>")

    html_parts.append(
        '<div class="footer">Generated by Ryan\'s Data Lab</div>'
    )
    html_parts.append("</body></html>")
    return "\n".join(html_parts)


def render_download_report_button(title: str, sections: list, key: str = "dl_report"):
    """Render a download button for an HTML report."""
    html = generate_report_html(title, sections)
    st.download_button(
        label="Download Report (HTML)",
        data=html,
        file_name=f"{title.lower().replace(' ', '_')}_report.html",
        mime="text/html",
        key=key,
    )


# ─── Content helpers ────────────────────────────────────────────────────────

def _content_preview(content, max_chars=200):
    """Return a short plain-text preview of section content."""
    if isinstance(content, pd.DataFrame):
        preview = f"DataFrame ({content.shape[0]} rows x {content.shape[1]} cols)"
        if len(content) > 0:
            cols_str = ", ".join(content.columns[:5].tolist())
            if len(content.columns) > 5:
                cols_str += f" ... +{len(content.columns) - 5} more"
            preview += f" | Columns: {cols_str}"
        return preview
    elif hasattr(content, "to_image") or hasattr(content, "to_html"):
        # Plotly figure
        title = ""
        if hasattr(content, "layout") and hasattr(content.layout, "title"):
            t = content.layout.title
            if hasattr(t, "text") and t.text:
                title = t.text
        return f"Plotly Figure{': ' + title if title else ''}"
    else:
        text = str(content)
        # Strip HTML tags for preview
        import re
        text = re.sub(r"<[^>]+>", " ", text)
        text = re.sub(r"\s+", " ", text).strip()
        if len(text) > max_chars:
            text = text[:max_chars] + "..."
        return text if text else "(empty)"


def _fig_to_png_bytes(fig, width=900, height=500):
    """Convert a Plotly figure to PNG bytes using kaleido."""
    try:
        return fig.to_image(format="png", width=width, height=height)
    except Exception:
        return None


# ─── PDF export ─────────────────────────────────────────────────────────────

def _build_pdf(title, author, date_str, sections, include_logo):
    """Build a PDF report and return it as bytes."""
    if not _HAS_FPDF:
        return None

    class ReportPDF(FPDF):
        def __init__(self, report_title, report_author, report_date, logo):
            super().__init__()
            self.report_title = report_title
            self.report_author = report_author
            self.report_date = report_date
            self.include_logo = logo
            self._toc_entries = []

        def header(self):
            if self.page_no() == 1:
                return  # Title page has its own layout
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(148, 163, 184)
            self.cell(0, 8, self.report_title, align="L")
            self.ln(10)

        def footer(self):
            if self.page_no() == 1:
                return
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(148, 163, 184)
            self.cell(0, 10, f"Page {self.page_no() - 1}", align="C")

        def title_page(self):
            self.add_page()
            self.ln(60)
            if self.include_logo:
                self.set_font("Helvetica", "B", 12)
                self.set_text_color(99, 102, 241)
                self.cell(0, 10, "Ryan's Data Lab", align="C", new_x="LMARGIN", new_y="NEXT")
                self.ln(10)
            self.set_font("Helvetica", "B", 28)
            self.set_text_color(30, 41, 59)
            self.multi_cell(0, 14, self.report_title, align="C")
            self.ln(10)
            self.set_font("Helvetica", "", 14)
            self.set_text_color(100, 116, 139)
            if self.report_author:
                self.cell(0, 10, f"Author: {self.report_author}", align="C",
                          new_x="LMARGIN", new_y="NEXT")
            self.cell(0, 10, f"Date: {self.report_date}", align="C",
                      new_x="LMARGIN", new_y="NEXT")

        def table_of_contents(self, section_titles):
            self.add_page()
            self.set_font("Helvetica", "B", 18)
            self.set_text_color(30, 41, 59)
            self.cell(0, 12, "Table of Contents", new_x="LMARGIN", new_y="NEXT")
            self.ln(6)
            self.set_font("Helvetica", "", 12)
            self.set_text_color(51, 65, 85)
            for i, t in enumerate(section_titles, 1):
                self.cell(0, 8, f"  {i}. {t}", new_x="LMARGIN", new_y="NEXT")

        def section_heading(self, text):
            self.ln(6)
            self.set_font("Helvetica", "B", 16)
            self.set_text_color(99, 102, 241)
            self.cell(0, 10, text, new_x="LMARGIN", new_y="NEXT")
            # Draw underline
            self.set_draw_color(99, 102, 241)
            y = self.get_y()
            self.line(10, y, 200, y)
            self.ln(4)

        def section_body_text(self, text):
            self.set_font("Helvetica", "", 11)
            self.set_text_color(30, 41, 59)
            # Strip simple HTML tags
            import re
            text = re.sub(r"<[^>]+>", " ", text)
            text = re.sub(r"&mdash;", " -- ", text)
            text = re.sub(r"&nbsp;", " ", text)
            text = re.sub(r"&amp;", "&", text)
            text = re.sub(r"&lt;", "<", text)
            text = re.sub(r"&gt;", ">", text)
            text = re.sub(r"\s+", " ", text).strip()
            if text:
                self.multi_cell(0, 6, text)
            self.ln(2)

        def add_dataframe_table(self, df_obj):
            max_cols = min(len(df_obj.columns), 8)
            cols = df_obj.columns[:max_cols].tolist()
            max_rows = min(len(df_obj), 50)
            df_sub = df_obj.head(max_rows)

            avail_width = self.w - 2 * self.l_margin
            col_width = avail_width / max_cols

            # Header
            self.set_font("Helvetica", "B", 8)
            self.set_fill_color(241, 245, 249)
            self.set_text_color(30, 41, 59)
            for col in cols:
                label = str(col)[:15]
                self.cell(col_width, 7, label, border=1, fill=True)
            self.ln()

            # Rows
            self.set_font("Helvetica", "", 7)
            for _, row in df_sub.iterrows():
                for col in cols:
                    val = str(row[col])[:18]
                    self.cell(col_width, 6, val, border=1)
                self.ln()

            if len(df_obj) > max_rows:
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(148, 163, 184)
                self.cell(0, 6, f"  ... {len(df_obj) - max_rows} more rows",
                          new_x="LMARGIN", new_y="NEXT")
            if len(df_obj.columns) > max_cols:
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(148, 163, 184)
                self.cell(0, 6, f"  ... {len(df_obj.columns) - max_cols} more columns",
                          new_x="LMARGIN", new_y="NEXT")
            self.ln(4)

    pdf = ReportPDF(title, author, date_str, include_logo)
    pdf.set_auto_page_break(auto=True, margin=20)

    # Title page
    pdf.title_page()

    # Table of contents
    section_titles = [s["title"] for s in sections]
    pdf.table_of_contents(section_titles)

    # Sections
    for sec in sections:
        pdf.add_page()
        pdf.section_heading(sec["title"])
        content = sec["content"]

        if isinstance(content, pd.DataFrame):
            pdf.add_dataframe_table(content)
        elif hasattr(content, "to_image"):
            # Plotly figure - render as PNG
            png_data = _fig_to_png_bytes(content)
            if png_data:
                img_stream = io.BytesIO(png_data)
                pdf.image(img_stream, x=10, w=190)
                pdf.ln(4)
            else:
                pdf.section_body_text("[Chart could not be rendered - kaleido may not be available]")
        else:
            pdf.section_body_text(str(content))

        commentary = sec.get("commentary", "")
        if commentary:
            pdf.ln(2)
            pdf.set_font("Helvetica", "I", 10)
            pdf.set_text_color(100, 116, 139)
            pdf.multi_cell(0, 6, commentary)

    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()


# ─── PowerPoint export ──────────────────────────────────────────────────────

def _build_pptx(title, author, date_str, sections, include_logo):
    """Build a PowerPoint presentation and return it as bytes."""
    if not _HAS_PPTX:
        return None

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # --- Title slide ---
    slide_layout = prs.slide_layouts[0]  # Title Slide
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    subtitle_shape = slide.placeholders[1]
    subtitle_text = ""
    if author:
        subtitle_text += f"Author: {author}\n"
    subtitle_text += f"Date: {date_str}"
    if include_logo:
        subtitle_text += "\n\nRyan's Data Lab"
    subtitle_shape.text = subtitle_text

    # --- Section slides ---
    for sec in sections:
        slide_layout = prs.slide_layouts[5]  # Blank
        slide = prs.slides.add_slide(slide_layout)

        # Title text box at top
        from pptx.util import Inches, Pt, Emu
        title_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(0.3), Inches(12.3), Inches(0.8)
        )
        tf = title_box.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = sec["title"]
        p.font.size = Pt(28)
        p.font.bold = True
        p.font.color.rgb = _pptx_rgb(99, 102, 241)

        content = sec["content"]
        content_top = Inches(1.3)
        content_left = Inches(0.5)
        content_width = Inches(12.3)
        content_height = Inches(5.5)

        if isinstance(content, pd.DataFrame):
            _add_df_table_to_slide(slide, content, content_left, content_top,
                                   content_width, content_height)
        elif hasattr(content, "to_image"):
            # Plotly figure as PNG
            png_data = _fig_to_png_bytes(content, width=900, height=500)
            if png_data:
                img_stream = io.BytesIO(png_data)
                slide.shapes.add_picture(
                    img_stream, Inches(1.5), content_top,
                    width=Inches(10), height=Inches(5.2)
                )
            else:
                _add_text_to_slide(slide, "[Chart could not be rendered]",
                                   content_left, content_top, content_width, content_height)
        else:
            import re
            text = str(content)
            text = re.sub(r"<[^>]+>", " ", text)
            text = re.sub(r"&mdash;", " -- ", text)
            text = re.sub(r"&nbsp;", " ", text)
            text = re.sub(r"&amp;", "&", text)
            text = re.sub(r"\s+", " ", text).strip()
            _add_text_to_slide(slide, text, content_left, content_top,
                               content_width, content_height)

        # Commentary
        commentary = sec.get("commentary", "")
        if commentary:
            comment_box = slide.shapes.add_textbox(
                Inches(0.5), Inches(6.3), Inches(12.3), Inches(0.8)
            )
            ctf = comment_box.text_frame
            ctf.word_wrap = True
            cp = ctf.paragraphs[0]
            cp.text = commentary
            cp.font.size = Pt(12)
            cp.font.italic = True
            cp.font.color.rgb = _pptx_rgb(100, 116, 139)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


def _pptx_rgb(r, g, b):
    """Create a pptx RGBColor."""
    from pptx.dml.color import RGBColor
    return RGBColor(r, g, b)


def _add_text_to_slide(slide, text, left, top, width, height):
    """Add a text box to a slide."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    # Truncate very long text to keep slides readable
    if len(text) > 2000:
        text = text[:2000] + "..."
    p.text = text
    p.font.size = Pt(14)
    p.font.color.rgb = _pptx_rgb(30, 41, 59)


def _add_df_table_to_slide(slide, df_obj, left, top, width, height):
    """Add a DataFrame as a table on a slide."""
    max_cols = min(len(df_obj.columns), 8)
    max_rows = min(len(df_obj), 15)
    cols = df_obj.columns[:max_cols].tolist()
    df_sub = df_obj.head(max_rows)

    rows_count = max_rows + 1  # +1 for header
    cols_count = max_cols

    table_shape = slide.shapes.add_table(
        rows_count, cols_count, left, top, width,
        Inches(min(0.35 * rows_count, 5.0))
    )
    table = table_shape.table

    # Header row
    for c_idx, col_name in enumerate(cols):
        cell = table.cell(0, c_idx)
        cell.text = str(col_name)[:20]
        for paragraph in cell.text_frame.paragraphs:
            paragraph.font.size = Pt(10)
            paragraph.font.bold = True

    # Data rows
    for r_idx, (_, row) in enumerate(df_sub.iterrows()):
        for c_idx, col_name in enumerate(cols):
            cell = table.cell(r_idx + 1, c_idx)
            val = row[col_name]
            if isinstance(val, float):
                cell.text = f"{val:.4g}"
            else:
                cell.text = str(val)[:20]
            for paragraph in cell.text_frame.paragraphs:
                paragraph.font.size = Pt(9)


# ─── Auto-section generators ───────────────────────────────────────────────

def _generate_executive_summary(df):
    """Auto-generate an executive summary section from the dataset."""
    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()
    total_cells = df.shape[0] * df.shape[1]
    missing_count = df.isnull().sum().sum()
    missing_pct = (missing_count / total_cells * 100) if total_cells > 0 else 0.0

    summary_lines = [
        f"<p><strong>Dataset Overview</strong></p>",
        f"<ul>",
        f"<li><strong>Observations:</strong> {df.shape[0]:,} rows</li>",
        f"<li><strong>Variables:</strong> {df.shape[1]} columns "
        f"({len(num_cols)} numeric, {len(cat_cols)} categorical)</li>",
        f"<li><strong>Data Completeness:</strong> {100 - missing_pct:.1f}% "
        f"({missing_count:,} missing values, {missing_pct:.1f}% of all cells)</li>",
    ]

    if num_cols:
        summary_lines.append(f"<li><strong>Numeric columns:</strong> {', '.join(num_cols[:8])}"
                             f"{'...' if len(num_cols) > 8 else ''}</li>")
    if cat_cols:
        summary_lines.append(f"<li><strong>Categorical columns:</strong> {', '.join(cat_cols[:8])}"
                             f"{'...' if len(cat_cols) > 8 else ''}</li>")

    summary_lines.append("</ul>")
    return "\n".join(summary_lines)


def _generate_methodology(sections):
    """Auto-generate a methodology section based on analysis types detected."""
    titles_lower = [s["title"].lower() for s in sections]
    methods = []

    keyword_map = {
        "descriptive": "Descriptive statistics were computed to summarize central tendency, "
                       "dispersion, and distribution shape for numeric variables.",
        "correlation": "Correlation analysis was performed to assess pairwise linear relationships "
                       "between numeric variables using Pearson, Spearman, or Kendall coefficients.",
        "regression": "Regression modeling was applied to quantify the relationship between "
                      "predictor variables and the response variable.",
        "anova": "Analysis of Variance (ANOVA) was used to test for significant differences "
                 "in group means.",
        "hypothesis": "Hypothesis testing was conducted to evaluate statistical significance "
                      "of observed effects at the specified significance level.",
        "t-test": "Student's t-test (or Welch's variant) was used to compare means between groups.",
        "chi": "Chi-square testing was applied to evaluate associations between categorical variables.",
        "survival": "Survival analysis was performed to model time-to-event data using "
                    "Kaplan-Meier estimation and/or Cox proportional hazards regression.",
        "time series": "Time series analysis was conducted including trend decomposition, "
                       "stationarity testing, and/or forecasting models.",
        "machine learning": "Machine learning models were trained and evaluated using "
                            "cross-validation with appropriate performance metrics.",
        "distribution": "Distribution analysis was performed to characterize the shape "
                        "and properties of variable distributions.",
        "quality": "Statistical process control and quality analysis methods were applied.",
        "doe": "Design of experiments methodology was used to systematically evaluate "
               "factor effects.",
        "visualization": "Data visualization was used to explore patterns, trends, "
                         "and relationships in the data.",
    }

    for keyword, description in keyword_map.items():
        if any(keyword in t for t in titles_lower):
            methods.append(description)

    if not methods:
        methods.append("Statistical analyses were performed using Ryan's Data Lab. "
                       "Specific methods are detailed in individual report sections.")

    methodology = "<p><strong>Statistical Methods</strong></p><ul>"
    for m in methods:
        methodology += f"<li>{m}</li>"
    methodology += "</ul>"
    methodology += ("<p><em>All analyses were conducted using Ryan's Data Lab (RDL). "
                    "Visualizations were generated with Plotly. "
                    "Statistical significance was assessed at conventional thresholds "
                    "unless otherwise noted.</em></p>")
    return methodology


# ─── Live preview rendering ─────────────────────────────────────────────────

def _render_preview(sections, title, author, date_str):
    """Render a live preview of the report in the right column."""
    st.markdown(
        f'<div style="background:#f8fafc; border:1px solid #e2e8f0; border-radius:8px; '
        f'padding:20px; margin-bottom:12px;">'
        f'<h2 style="color:#6366f1; margin:0 0 4px 0;">{title}</h2>'
        f'<p style="color:#94a3b8; margin:0; font-size:0.85em;">'
        f'{author + " | " if author else ""}{date_str}</p>'
        f'</div>',
        unsafe_allow_html=True,
    )

    if not sections:
        st.caption("Sections will appear here as you add them.")
        return

    for i, sec in enumerate(sections):
        with st.container(border=True):
            st.markdown(f"**{sec['title']}**")
            content = sec["content"]
            if isinstance(content, pd.DataFrame):
                st.dataframe(content.head(10), use_container_width=True, hide_index=True)
                if len(content) > 10:
                    st.caption(f"Showing 10 of {len(content)} rows")
            elif hasattr(content, "to_html") or hasattr(content, "to_image"):
                # Plotly figure
                rdl_plotly_chart(content, key=f"preview_fig_{i}")
            else:
                text = str(content)
                if len(text) > 500:
                    st.markdown(text[:500] + "...", unsafe_allow_html=True)
                else:
                    st.markdown(text, unsafe_allow_html=True)

            commentary = sec.get("commentary", "")
            if commentary:
                st.caption(f"Note: {commentary}")


# ─── Main render function ──────────────────────────────────────────────────

def render_report_builder(df: pd.DataFrame):
    """Interactive report builder with section management, preview, and multi-format export."""

    section_header("Report Builder",
                   "Assemble analysis sections into a polished report. "
                   "Use 'Add to Report' buttons in analysis modules to collect sections, "
                   "then customize and export here.")

    # Initialize report sections in session state
    if "report_sections" not in st.session_state:
        st.session_state["report_sections"] = []

    sections = st.session_state["report_sections"]

    # ── Global settings ──────────────────────────────────────────────────
    with st.expander("Report Settings", expanded=True):
        s1, s2, s3 = st.columns([2, 2, 1])
        with s1:
            report_title = st.text_input("Report Title",
                                         value="Data Analysis Report",
                                         key="rb_title")
        with s2:
            report_author = st.text_input("Author", value="", key="rb_author")
        with s3:
            report_date = st.date_input("Date", value=datetime.now(), key="rb_date")

        include_logo = st.toggle("Include RDL branding", value=True, key="rb_logo")

    date_str = report_date.strftime("%Y-%m-%d") if report_date else datetime.now().strftime("%Y-%m-%d")

    # ── Auto-sections ────────────────────────────────────────────────────
    st.divider()
    a1, a2, a3 = st.columns(3)
    with a1:
        if st.button("Add Executive Summary", key="rb_auto_exec",
                      use_container_width=True,
                      disabled=(df is None or (df is not None and df.empty))):
            if df is not None and not df.empty:
                summary_html = _generate_executive_summary(df)
                st.session_state["report_sections"].append({
                    "title": "Executive Summary",
                    "content": summary_html,
                    "timestamp": datetime.now().isoformat(),
                })
                st.rerun()
    with a2:
        if st.button("Add Methodology", key="rb_auto_method",
                      use_container_width=True,
                      disabled=(len(sections) == 0)):
            methodology_html = _generate_methodology(sections)
            st.session_state["report_sections"].append({
                "title": "Methodology",
                "content": methodology_html,
                "timestamp": datetime.now().isoformat(),
            })
            st.rerun()
    with a3:
        if st.button("Clear All Sections", key="rb_clear",
                      type="secondary", use_container_width=True,
                      disabled=(len(sections) == 0)):
            st.session_state["report_sections"] = []
            st.rerun()

    st.divider()

    # ── Two-column layout: management (left) + preview (right) ───────────
    if not sections:
        empty_state(
            "No sections added yet.",
            "Use 'Add to Report' buttons in analysis modules, or add an "
            "Executive Summary above to get started."
        )
        return

    col_manage, col_preview = st.columns([1, 1], gap="large")

    # ── Left column: section management ──────────────────────────────────
    with col_manage:
        st.markdown(f"**Sections ({len(sections)})**")

        for i, sec in enumerate(sections):
            with st.container(border=True):
                # Title + controls row
                tc1, tc2, tc3, tc4 = st.columns([5, 1, 1, 1])
                with tc1:
                    new_title = st.text_input(
                        "Section title",
                        value=sec["title"],
                        key=f"rb_sec_title_{i}",
                        label_visibility="collapsed",
                    )
                    if new_title != sec["title"]:
                        st.session_state["report_sections"][i]["title"] = new_title
                with tc2:
                    if st.button("Up", key=f"rb_up_{i}",
                                  disabled=(i == 0),
                                  use_container_width=True):
                        s = st.session_state["report_sections"]
                        s[i], s[i - 1] = s[i - 1], s[i]
                        st.rerun()
                with tc3:
                    if st.button("Dn", key=f"rb_dn_{i}",
                                  disabled=(i == len(sections) - 1),
                                  use_container_width=True):
                        s = st.session_state["report_sections"]
                        s[i], s[i + 1] = s[i + 1], s[i]
                        st.rerun()
                with tc4:
                    if st.button("Del", key=f"rb_del_{i}",
                                  type="secondary",
                                  use_container_width=True):
                        st.session_state["report_sections"].pop(i)
                        st.rerun()

                # Commentary
                commentary = st.text_area(
                    "Commentary (optional)",
                    value=sec.get("commentary", ""),
                    key=f"rb_commentary_{i}",
                    height=68,
                    placeholder="Add notes or interpretation below this section...",
                )
                if commentary != sec.get("commentary", ""):
                    st.session_state["report_sections"][i]["commentary"] = commentary

                # Content preview
                preview = _content_preview(sec["content"])
                st.caption(f"Content: {preview}")
                ts = sec.get("timestamp", "")
                if ts:
                    try:
                        dt = datetime.fromisoformat(ts)
                        st.caption(f"Added: {dt.strftime('%H:%M:%S')}")
                    except (ValueError, TypeError):
                        pass

    # ── Right column: live preview ───────────────────────────────────────
    with col_preview:
        st.markdown("**Live Preview**")
        # Build enriched sections with commentaries from UI
        preview_sections = []
        for i, sec in enumerate(st.session_state["report_sections"]):
            enriched = dict(sec)
            enriched["commentary"] = sec.get("commentary", "")
            preview_sections.append(enriched)

        _render_preview(preview_sections, report_title, report_author, date_str)

    # ── Export buttons ───────────────────────────────────────────────────
    st.divider()
    section_header("Export Report")

    # Prepare enriched sections for export
    export_sections = []
    for i, sec in enumerate(st.session_state["report_sections"]):
        enriched = dict(sec)
        enriched["commentary"] = sec.get("commentary", "")
        export_sections.append(enriched)

    ex1, ex2, ex3 = st.columns(3)

    # HTML export
    with ex1:
        html_data = generate_report_html(report_title, export_sections)
        st.download_button(
            label="Download HTML",
            data=html_data,
            file_name=f"{report_title.lower().replace(' ', '_')}_report.html",
            mime="text/html",
            key="rb_export_html",
            use_container_width=True,
        )

    # PDF export
    with ex2:
        if not _HAS_FPDF:
            st.button("Download PDF", disabled=True, key="rb_export_pdf_disabled",
                       use_container_width=True)
            st.caption("Install fpdf2: `pip install fpdf2`")
        else:
            with st.spinner("Building PDF..."):
                try:
                    pdf_bytes = _build_pdf(report_title, report_author, date_str,
                                           export_sections, include_logo)
                    if pdf_bytes:
                        st.download_button(
                            label="Download PDF",
                            data=pdf_bytes,
                            file_name=f"{report_title.lower().replace(' ', '_')}_report.pdf",
                            mime="application/pdf",
                            key="rb_export_pdf",
                            use_container_width=True,
                        )
                    else:
                        st.button("Download PDF", disabled=True,
                                   key="rb_export_pdf_err",
                                   use_container_width=True)
                        st.caption("PDF generation failed.")
                except Exception as e:
                    st.button("Download PDF", disabled=True,
                               key="rb_export_pdf_exc",
                               use_container_width=True)
                    st.caption(f"PDF error: {e}")

    # PowerPoint export
    with ex3:
        if not _HAS_PPTX:
            st.button("Download PPTX", disabled=True, key="rb_export_pptx_disabled",
                       use_container_width=True)
            st.caption("Install python-pptx: `pip install python-pptx`")
        else:
            with st.spinner("Building PPTX..."):
                try:
                    pptx_bytes = _build_pptx(report_title, report_author, date_str,
                                             export_sections, include_logo)
                    if pptx_bytes:
                        st.download_button(
                            label="Download PPTX",
                            data=pptx_bytes,
                            file_name=f"{report_title.lower().replace(' ', '_')}_report.pptx",
                            mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                            key="rb_export_pptx",
                            use_container_width=True,
                        )
                    else:
                        st.button("Download PPTX", disabled=True,
                                   key="rb_export_pptx_err",
                                   use_container_width=True)
                        st.caption("PPTX generation failed.")
                except Exception as e:
                    st.button("Download PPTX", disabled=True,
                               key="rb_export_pptx_exc",
                               use_container_width=True)
                    st.caption(f"PPTX error: {e}")

    st.caption(f"Report contains {len(export_sections)} section(s). "
               f"All exports include section titles, content, and commentary.")
